title: putrequest_
description: "Strona koła naukowego putrequest_"
author:
  name: "putrequest_"
  email: "dev@null.pl"
  url: "https://putrequest.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:categories/:title/
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "putrequest_"
year : "2022"
